stages:
  - test
  - deploy

test:
  stage: test
  script:
    # Run unit tests
    - pytest
  artifacts:
    paths:
      - test_results.xml

deploy:
  stage: deploy
  script:
    # Install dependencies
    - pip install -r requirements.txt
    
  artifacts:
    paths:
      - deploy_log.txt
